sudo: false

language: node_js

node_js:
  - "0.10.41"


before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - "npm install -g meteorite laika"
  - export PATH="$HOME/.meteor:$PATH"

services:
  - mongodb

env:
  - LAIKA_OPTIONS="-t 5000"

script: "laika -t 5000"
